TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

DB += pvStats-nlcta.db
DB += pvStats-asta.db
DB += scope.db

include $(TOP)/configure/RULES
